### PR TITLE
scrape-data: don't perform a commit / rebuild if only meta.json changes

### PR DESCRIPTION
**Pull request by johnnyapol**

### CODE REVIEW

**Comment by benjaminrsherman** [comment]
I believe the metadata controls the indicator on QuACS which shows when the data was last updated.  If that's the case, we want to always commit and deploy so it's clear that we're up to date.

**Comment by elihschiff** [comment]
I am good with either way. I actually tried to do this originally but my code didn't work so I just removed it.

**Comment by johnnyapol** [comment]
I can understand the concern for the last updated indicator. Personally, I'd prefer for it to refer when something actually changes in the data / site, rather than just a mere daily refresh -- especially for the periods of time where we're in post-initial schedule release changes.

If you come to the consensus the current behavior is preferred, feel free to close this out.

**Comment by benjaminrsherman** [comment]
> I'd prefer for it to refer when something actually changes in the data / site, rather than just a mere daily refresh

I agree with this, and ideally this wouldn't cause any issues, but I'm still worried about the new user experience.  People care about when the data was last up to date, not when there was a change.  For the average, non-QuACS developer, user it won't matter if classes haven't changed for weeks: if QuACS says it was updated weeks ago, it won't be trusted.

A better alternative could be to include a message on hovering over the update time like "RPI last changed course times X hours ago", though that would be a more complicated change.

**Comment by elihschiff** [comment]
What if we switch it so that when quacs builds it looks for the last successful run of the data scrape github action and hard codes that value into the website. Then we can have it build after the rescrape action finishes regardless of it the data was updated or not.

**Comment by benjaminrsherman** [comment]
If you're able to get when the last successful run was, that works for me.

**Pull request closed without merging**
